# A003: ignore column name collisions with builtins (eg 'id')
# D103: don't need docstrings for migrations functions
# D107: don't need docstrings for __init__ method of classes. 
#       Infavor of documenting at the top of classes instead of inside __init__ methods.
# D203: 1 blank line required before class docstring.
# W503: Line breaks should occur after the binary operator to keep 
#       all variable names aligned. Disabled infavor of W504 (PEP8 updates)
[tool.flakehell]
# Added per https://githubmemory.com/repo/flakehell/flakehell/issues/10
# exclude chat_rendering.py until tested/fixed
extended_default_ignore=['chat_rendering.py'] 
format = 'grouped'
max_line_length = 88
show_source = true
docstring-convention = 'google'
inline-quotes = 'double'

[tool.flakehell.plugins]
flake8-bandit = ['+*']
flake8-bugbear = ['+*']
flake8-builtins = ['+*']
flake8-commas = ['+*']
flake8-comprehensions = ['+*']
flake8-darglint = ['+*']
flake8-docstrings = ['-+*', '-D107']
flake8-eradicate = ['+*']
flake8-isort = ['+*']
flake8-mutable = ['+*']
flake8-pytest-style = ['+*']
flake8-quotes = ['+*', '-Q000']
flake8-variables-names = ['+*']
mccabe = ['+*']
pep8-naming = ['+*']
pycodestyle = ['+*', '-D203', '-W503', '-E501', '-E203']
pyflakes = ['+*']
pylint = ['+F*', '+E*', '-E0611', '-E1101', '-E0401', '-E1102', '-E1123']

[tool.flakehell.exceptions.'**/__init__.py']
pyflakes = ['-F401']

[tool.flakehell.exceptions.'ileapp/helpers/db.py']
pyflakes = ['-F841']

[tool.isort]
profile = 'black'
multi_line_output = 3
line_length = 88
include_trailing_comma = true
skip = ['.eggs',
        '.git',
        '.venv',
        '_build',
        'venv']

[tool.black]
line_length = 88
target_version = ['py39']
exclude = '''
^/(
  (
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
  )/
)
'''
